### ISSUE TITLE
Question about Mask Transfer and  ImageNet Tickets

### ISSUE THREAD

**Issue by dashu233** [Sharath-girish/LTH-ObjectRecognition#5]
Hi, Sharath-girish, I have read about your paper 'The Lottery Ticket Hypothesis for Object Recognition '.  I find your research is interesting.  I'm confused about the notion of Mask Transfer. It seems that it has a better performance than ImageNet Tickets in Appendix Table 1. However, I can't reproduce this result by my own code so I guess I miss some important parts. Could you please tell me what's the difference between Mask Transfer and ImageNet Tickets? In my opinion, Mask Transfer is just an ImageNet Ticket with NUM_ROUND=1.

**Comment by abhyantrika** [comment]
Hi, 
Mask transfer refers to transferring only the binary mask of the winning ticket, devoid of the values, to another randomly initialized network. 
The idea is that the mask structure of LTH itself contains useful information and priors.

**Comment by dashu233** [comment]
> Hi, Mask transfer refers to transferring only the binary mask of the winning ticket, devoid of the values, to another randomly initialized network. The idea is that the mask structure of LTH itself contains useful information and priors.

Thank you for your reply! I understand my mistakes. However, based on my experience, training from scratch in coco dataset should take a long time for training and a pruned network (even in lth setting) will be hard to converge. Do you still use 1x setting to run this experiment or use more training epochs? This will be helpful for my reproducing, thanks.
